"""add is_blocked and is_deleted attributes in blob

Revision ID: 7742b916ddc5
Revises: b2125d1c7299
Create Date: 2025-07-19 22:52:23.047595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7742b916ddc5'
down_revision: Union[str, Sequence[str], None] = 'b2125d1c7299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('blogs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'is_deleted')
    op.drop_column('blogs', 'is_blocked')
    # ### end Alembic commands ###
