"""add is_deleted and updated_at to feedback

Revision ID: 78925e8b2f60
Revises: 56c5f580d968
Create Date: 2025-07-19 10:02:51.232176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78925e8b2f60'
down_revision: Union[str, Sequence[str], None] = '56c5f580d968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('feedbacks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'updated_at')
    op.drop_column('feedbacks', 'is_deleted')
    # ### end Alembic commands ###
