from decouple import config


DATABASE_URL = config("DATABASE_URL")
SECRET_KEY = config("SECRET_KEY")

AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_KEY")
AWS_REGION = config("AWS_REGION_NAME")
AWS_BUCKET_NAME = config("AWS_BUCKET_NAME")

